Library installed and then when importing, I get:
```
In [1]: import M2Crypto
Fatal Python error: SWIG/_m2crypto_wrap.c:1234 object at 0x7fe2a5867c00 has negative ref count -1

Thread 0x00007fe297afc700:
  File "/usr/lib/python3.3/site-packages/IPython/core/history.py", line 591 in _writeout_input_cache
  File "/usr/lib/python3.3/site-packages/IPython/core/history.py", line 607 in writeout_cache
  File "/usr/lib/python3.3/site-packages/IPython/core/history.py", line 60 in needs_sqlite
  File "<string>", line 2 in writeout_cache
  File "/usr/lib/python3.3/site-packages/IPython/core/history.py", line 656 in run
  File "/usr/lib/python3.3/site-packages/IPython/core/history.py", line 60 in needs_sqlite
  File "<string>", line 2 in run
  File "/usr/lib64/python3.3/threading.py", line 637 in _bootstrap_inner
  File "/usr/lib64/python3.3/threading.py", line 614 in _bootstrap

Current thread 0x00007fe2a5895740:
  File "/home/matej/.local/lib/python3.3/site-packages/M2Crypto-0.22.dev-py3.3-linux-x86_64.egg/M2Crypto/__m2crypto.py", line 6 in __bootstrap__
  File "/home/matej/.local/lib/python3.3/site-packages/M2Crypto-0.22.dev-py3.3-linux-x86_64.egg/M2Crypto/__m2crypto.py", line 7 in <module>
  File "<frozen importlib._bootstrap>", line 313 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 870 in _load_module
  File "<frozen importlib._bootstrap>", line 562 in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 1005 in load_module
  File "<frozen importlib._bootstrap>", line 1024 in load_module
  File "<frozen importlib._bootstrap>", line 586 in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1534 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1567 in _find_and_load
  File "<frozen importlib._bootstrap>", line 313 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1616 in _handle_fromlist
  File "/home/matej/.local/lib/python3.3/site-packages/M2Crypto-0.22.dev-py3.3-linux-x86_64.egg/M2Crypto/__init__.py", line 22 in <module>
  File "<frozen importlib._bootstrap>", line 313 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 870 in _load_module
  File "<frozen importlib._bootstrap>", line 562 in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 1005 in load_module
  File "<frozen importlib._bootstrap>", line 1024 in load_module
  File "<frozen importlib._bootstrap>", line 586 in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1534 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1567 in _find_and_load
  File "<ipython-input-1-ddb19dac35a9>", line 1 in <module>
  File "/usr/lib/python3.3/site-packages/IPython/core/interactiveshell.py", line 2732 in run_code
  File "/usr/lib/python3.3/site-packages/IPython/core/interactiveshell.py", line 2676 in run_ast_nodes
  File "/usr/lib/python3.3/site-packages/IPython/core/interactiveshell.py", line 2603 in run_cell
  File "/usr/lib/python3.3/site-packages/IPython/frontend/terminal/interactiveshell.py", line 586 in interact
  File "/usr/lib/python3.3/site-packages/IPython/frontend/terminal/interactiveshell.py", line 467 in mainloop
  File "/usr/lib/python3.3/site-packages/IPython/frontend/terminal/ipapp.py", line 363 in start
  File "/usr/lib/python3.3/site-packages/IPython/frontend/terminal/ipapp.py", line 389 in launch_new_instance
  File "/usr/bin/ipython3", line 9 in <module>
Aborted (core dumped)
matej@wycliff: ~$ 
```